[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.5.1" }
selene = { source = "Kampfkarren/selene", version = "0.27.1" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.20.0" }
testez = { source = "Roblox/testez", version = "0.4.1" }
wally = { source = "UpliftGames/wally", version = "0.3.2" }
