# StyLua configuration for Roblox Luau projects
column_width = 100
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"

[sort_requires]
enabled = false  # Don't sort requires automatically as Roblox has specific loading order requirements
