[package]
name = "rbgg/prompt2play"
description = "Roblox Game Generation Pipeline - AI-powered template-first game creation system"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TestEZ = "roblox/testez@^0.4.1"

[server-dependencies]

[dev-dependencies]
